# site settings
title: Jiten
subtitle: Dhandha
baseurl: ""
url: ""

# homepage tiles
tiles-count: 6

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/JitenDhandha
  Twitter: https://x.com/currysmologist

# build settings
markdown: kramdown

sass:
  style: compressed
  quiet_deps: true

include:
  - _pages

exclude:
- "*.gemspec"
- README.md 